export class User {
    constructor(
        public id: number,
        public groupid: number,
        public user_type_id: number,
        public username: string,
        public level: string,
        public firstname: string,
        public lastname: string,
        public phone: string = null,
        public email: string,
        public activation_code : string,
        public forgotten_password_code : string,
        public forgotten_password_time : string,
        public remember_code: string,
        public last_login: string,
        public is_online: number = null,
        public active: number = null,
        public company: string = null,
        public picture: string = null,
        public ip_address: string,
        public status: string,
        public createby: number,
        public datecreate: string,
        public dateupdate: string,
        public tag:string,
        public code:string = null,
        public id_facebook: string  = null,
        public avatar: string = null,
        public last_login_datetime: string = null,
        public remember_key: string = null,
        public active_session: string = null,
        public status_chat: string,
        public is_first: number,
        
        public check: boolean = false,
    ) {
    }
}